### ISSUE TITLE
Devtools getting page expired 419

### ISSUE THREAD

**Issue by backpack-operations** [Laravel-Backpack/community-forum#1060]
Hello Team,

I just received this on email:

"I bought Devtools about 2 weeks ago and decided to use this weekend.

However, when I start the Devtools I get the following error:
<img width="1631" alt="backpackforlaravel Screenshot 2024-06-30 at 08 07 15" src="https://github.com/Laravel-Backpack/community-forum/assets/144793034/5588277e-9c7a-4b6b-bcce-3d4b82947cee">
"

**Comment by karandatwani92** [comment]
Hey @backpack-operations 

This happens because the `APP_URL` in the `.env` file is not correctly set. 

Make sure the `APP_URL` in your .env file is correctly pointing to the URL you use to access your application in the browser, for example: `http:127.0.0.1:8000` or `http://something.test`

If you are using `php artisan serve` to serve your application in `http://127.0.0.1:8000`, that's what you need to write in `APP_URL`. 

Cheers

**Comment by gequz** [comment]
Hey guys, this solved the issue, a big thank you!! :)
Apologies for the delayed response, it took me a while to login to GitHub.
Btw, is there a way to email issues to your GitHub support page instead of logging in?

Many thanks
