### ISSUE TITLE
[Feature Request] Add Config Entries For Custom App Paths

### ISSUE THREAD

**Issue by ghost** [Laravel-Backpack/community-forum#109]
When developing for clients, or for personal preference, many times you will end up changing the default directory structure of the application. 

For instance, in the app I was planning on using this for, the company required main directories to be in the top level namespace.

```
App\Controllers
App\Middleware
App\Models
App\Requests
...
```
So any package we use must adhere to this or be customizable. 

Now I could fork and re-write the namespace for all the crud generators, but it seems it would be trivial to create some additional fqn entries in the config corresponding to all the classes that have generators so that the generator can create the correct namespace for the class and place it correctly.

```
controller_fqn => 'Controllers\Admin',
...
```

Then inside the generator class:

```
/**
 * Get the default namespace for the class.
 *
 * @param string $rootNamespace
 *
 * @return string
 */
protected function getDefaultNamespace($rootNamespace)
{
    if (config('backpack.base.controller_fqn')) {
        return $rootNamespace. config('backpack.base.controller_fqn');
    }
    
    return $rootNamespace . '\Http\Controllers\Admin';
}
```

or something similar.

Unfortunately as it sits now I'll have to hack the generators in some fashion to use Backpack, or move all the classes by hand and then edit them :(

I'm happy to fork and submit pull requests if needed.

Thanks

**Comment by tabacitu** [comment]
Hi there,

Since there hasn't been much interest in this, I don't think we're going to do it. I do see the usefulness of this, but I don't think many people need this level of customization when the files are generated, so building it doesn't make much sense. 

I think it's much easier to... generate everything where it is (using the Laravel conventions), then at the end move stuff around. IDEs like PHPStorm make this ridiculously easy. Plus... I don't think it's a great idea to NOT stick to the conventional Laravel folder structure. 

Sorry to close this - open to other suggestions of course.
Cheers!
