### ISSUE TITLE
Columns should probably have the ellipsis configurable

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/community-forum#119]
When a column text is trucated, it now shows three dots at the end (`...` - see https://github.com/Laravel-Backpack/CRUD/pull/3993). 

What if someone wants to change that?

It should probably be configurable.

**Comment by tabacitu** [comment]
The only reason we don't have this already is that... nobody asked for this it. If nobody _asked_ to make it configurable... we probably _shouldn't_. Otherwise... where do we stop making things configurable?

If you stumble onto this issue because you needed to configure this and couldn't, please reply and let us know 🙏

**Comment by margarizaldi** [comment]
Sure we need this. It's not so practical to view/edit each entry just to completely read (eg. comments, addresses, etc.).

Worse case, setting's (add on) description which is hidden in edit page will never be readable once we describe it a bit longer.

**Comment by tabacitu** [comment]
@margarizaldi I think you're referring to something else. This issue is about being able to change the `...` at the end to something else (like `---` or whatever). What you probably want is to increase the character limit after which `...` gets shown... correct? If so, you can use the `limit` attribute on column, and if you specify `100` or something, the `...` will only show after 100 characters. Not all columns have a `limit`, but most frequent ones do.

**Comment by margarizaldi** [comment]
@tabacitu ahaha sorry for my misunderstanding. Actually I was trying to find it (to modify the limit) and didn't find it yet. Since it was not my priority, I decided to find it later. Thanks for your help anyway.

Talking about the elipsis, I believe every configurable thing is **always good** since it doesn't sacrifice performance, causing bugs, etc.

But there are still many more valuable things to make backpack even better. Cheers🥂
