### ISSUE TITLE
[Feature Request] favicon setting

### ISSUE THREAD

**Issue by guleswine** [Laravel-Backpack/community-forum#138]
# Feature Request

### What's the feature you think Backpack should have?

Set custom favicon for admin panel

### Have you already implemented a prototype solution, for your own project?

We can to override 
`vendor/backpack/crud/src/resources/views/base/inc/head.blade.php`
and add something like 
`<link rel="icon" href="{{ url('uploads/site/icon.png') }}">`
but it seems to me that for such simple things overriding is a bad option

maybe I'm wrong and it's already configured somehow easier?

**Comment by tabacitu** [comment]
What I would personally like is to have the Backpack logo (the new one, coming soon, not the current old one) as the logo for the admin panel. But I don't know how many people would be ok with that... The idea behind that is for admins to be able to save the admin panel on their iOS / Android devices as apps, in which case the favicon would be important. It would also be useful on the desktop, for the admin to know if they're on a front-end page... or the admin panel...

But again... that would basically involved pushing the Backpack branding onto the admin panel, so it would require one more step (to remove that branding) in order to make it white-label. Don't know how many devs would prefer separate admin panel branding, and how many would prefer to use their own branding...

**Comment by mialex** [comment]
> Wait... we can already do that, can't we? We can create a resources/views/vendor/backpack/base/inc/head.blade.php that would include:

@tabacitu , no, I think you can not do it that way. When the system will try to resolve `'backpack::inc.head'` it will resolve to the overwritten file under `resources/views/vendor/backpack/base/inc/head.blade.php` and then cash this template to the path. Once you try to include template `@include('backpack::inc.head')` it will be resolver to the `resources/views/vendor/backpack/base/inc/head.blade.php` again and as a result, you will get a recursion. 

Is there a better way?

**Comment by pxpm** [comment]
Maybe include the file directly without using the view namespace so it doesn't get resolved by Laravel container?

**Comment by guleswine** [comment]
> Wait... we can already do that, can't we? We can create a `resources/views/vendor/backpack/base/inc/head.blade.php` that would include:

its sounds like true, but i try @include('backpack::inc.head') or @extends(backpack_view('inc.head')) and recive 500 error


probably @mialex  was right
> @tabacitu , no, I think you can not do it that way. When the system will try to resolve `'backpack::inc.head'` it will resolve to the overwritten file under `resources/views/vendor/backpack/base/inc/head.blade.php` and then cash this template to the path. Once you try to include template `@include('backpack::inc.head')` it will be resolver to the `resources/views/vendor/backpack/base/inc/head.blade.php` again and as a result, you will get a recursion.



> Don't know how many devs would prefer separate admin panel branding, and how many would prefer to use their own branding...

what about this, i think every site should have own brand, but even if I discard my preferences, two open tabs of different panels based on the backpack will merge ;)

**Comment by Devotom** [comment]
Hello,
@tabacitu for my working but I put <link rel="shortcut icon" href="{{ asset('public/favicon.ico') }}"> on vendor->crud->src->resources->views->inc->head.blade.php

**Comment by pxpm** [comment]
We now have a meta/favicon generator. You just need to replace the images with your own: https://backpackforlaravel.com/docs/6.x/base-how-to#publish-mobile-and-favicon-headers-and-assets-1

Cheers
