### ISSUE TITLE
[Feature Request] @field and @label directives for custom views/forms

### ISSUE THREAD

**Issue by flap152** [Laravel-Backpack/community-forum#186]
# Feature Request - `@field` and `@label`  directives for custom views/forms.

### What's the feature you think Backpack should have?

The ability to use `@field` in custom form blades in show/edit modes. In most use cases, this would also require the label for all fields to be optional, toggled by a $blade-crud variable. Then we use @labels directives to place the labels exactly where we want then in relation to the `@field`

### Have you already implemented a prototype solution, for your own project?

Yes. I might be able to submit a PR, but would definitely bea ble to share what we've done

### Do you see this as a core feature or an add-on?

I think it must be in core. 
It requires an `@if()` in each field.blade.php to make the label optional

Example form uses:
![image](https://user-images.githubusercontent.com/12900351/143608082-61b3213a-d7b1-4141-8857-e83bf766c24e.png)
![image](https://user-images.githubusercontent.com/12900351/143609353-65f3a5b8-719d-450a-90f0-17a49d4d8f79.png)

**Comment by tabacitu** [comment]
Cleaning up old issues. Been thinking about this... rather than add a new Blade directive for this, I would rather people use `@include()` or the component syntax itself. Fewer steps, easier to understand. So I gotta say "no" to this one. Good idea, but not worth the trouble imho.

Thanks for the suggestion, but sorry it didn't make the cut. Don't take this the wrong way please, 80% of my ideas don't make it either 😅
