### ISSUE TITLE
[Feature Request] Add Backpack API

### ISSUE THREAD

**Issue by masrodjie** [Laravel-Backpack/community-forum#192]
I've idea to add backpack API. This useful for who using SPA frontend like Svelte, Vue or React as alternative their interface.
The API is consist with GET, POST, PUT and DELETE for each CRUD.
GET is mapping with setupListOperation. So the fields in the GET same with columns defined in the setupListOperation. It's like datatable response in the current version (ex: /admin/category/search?persistent-table=true).
Same with POST is mapping setupCreateOperation.
Also don't forget with authentication. Maybe use built in sanctum to simplify.

**Comment by tabacitu** [comment]
Thanks for letting us know @masrodjie . It's been asked before and... to be honest... I've never understood why... Maybe you can explain it to me a bit. @abbyjanke maybe you can jump in too, I know you were rooting for a Backpack API too?

**Why don't I understand why people ask for a Backpack API?**

The way I see it, your SPA front-end doesn't _actually_ need a Backpack API. Because the front-end doesn't do admin stuff, it does user stuff. So it _actually_ needs an API to the Eloquent Models, directly. Which granted, are the basis of your admin stuff too 😅 But what I'm saying here is... there are already very _very_ good solutions for API for Eloquent Models. Personally I prefer [Laravel JSON:API](https://laraveljsonapi.io/) which I think is easy-to-understand, easy-to-use and standards-compliant. Others might prefer other APIs, of course. I don't see how a Backpack API would be better than that, to be honest...

What I'm trying to say here is that:
- I don't see the SPA API as being the admin panel's responsibility;
- even if it were its responsibility, I don't think we should create a new API, there are already a few GREAT ones, so we can re-use those;
- if there are already great ones... what else can we do, to make it easier for the dev? maybe make it easier to use them? I guess we could add a generator for our preferred API... or an interface in DevTools to generate as-close-as-possible schemas for it...

Is my logic flawed somewhere here @masrodjie & @abbyjanke ? What's your point of view on the above? What Laravel API solutions have you tried and liked/disliked? Could solving this "problem" be as simple as recommending a few Laravel API Projects?

Thanks for helping me understand this better.
Cheers!
