### ISSUE TITLE
[Feature] Dropzone field

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/community-forum#20]
Because ```repeatable``` strips away the ```name``` of the inputs, it's currently impossible to use ```upload``` and ```upload_multiple``` fields inside a ```repeatable``` group. That should be fine to begin with, since we have an alternative - the ```browse``` and ```browse_multiple``` fields. 

But. We _should_ provide direct-upload support inside repeatable, somehow, without depending on third-party libraries like elFinder. Installing elFinder just to be able to upload files inside repeatable is totally overkill. 

I see two possible solutions:
- (A) redo the ```repeatable``` field in a way that would NOT strip out the name;
- (B) create a new field that will allow us to upload files inside repeatable; and I think this is the perfect opportunity to implement a kickass ```dropzone``` field, especially since the heavy lifting has already been done in https://github.com/Gaspertrix/laravel-backpack-dropzone-field

**Comment by MeerKatDev** [comment]
any news on this? I just stumbled on needing this and it would be good at least to know what should be modified in order to make it work :)

**Comment by o15a3d4l11s2** [comment]
Just recently I had an interesting use case: the need to upload multiple files and add user-readable names to them. Naturally the first idea that came to my mind was: repeatable with 2 fields inside - text and upload. For the short term I am rolling my own implementation, but I think it might be actually better if it is possible to use upload in repeatable, rather than switching to dropzone.

**Comment by o15a3d4l11s2** [comment]
Short after writing this I see your plants for the repeatable (https://github.com/Laravel-Backpack/CRUD/pull/3439#issuecomment-923055430) and I am happy, because it should also resolve this issue.

**Comment by pxpm** [comment]
@o15a3d4l11s2 yes, I also think that refactoring repeatable would fix this issue. It's in my top priorities for 4.2

Can't wait! 🙏

**Comment by myasirhashmi** [comment]
Is there any update on this ? I am trying to use `repeatable` field with `subfields` to allow add file title and an attachment. Is there any suggested alternative for this ?

**Comment by realtebo** [comment]
Hi !

We're facing the same problem and need

We can use a field of type image but not a field of type 'upload' as subfield.

Is there any workaround (for version 5)?

**Comment by jfelixoptimiumnc** [comment]
+1

**Comment by tabacitu** [comment]
Good news everyone: we've prioritized this as the next feature we're going to build, as part of CRUD 5.5. 

@pxpm will spearhead these efforts as soon as we get 5.4 out the door (which includes support for millions/billions of records and a `morphTo` subfield 😱).

Thanks everyone for your patience on this 🙏

**Comment by tabacitu** [comment]
Just to be clear: this will be solved as a new field type... `dropzone` or `media`, something like that. NOT as a refactoring of `upload` and `upload_multiple`. That would mean too many changes, so many that they're completely different fields.

**Comment by tabacitu** [comment]
Update: there'a already a working dropzone field in https://github.com/prodixx/dropzone-field-for-backpack - so maybe we take inspiration from it, include @prodixx or something like that. Maybe we could save some time that way!

**Comment by o15a3d4l11s2** [comment]
I would suggest drafting some constraints, as this field could become quite complicated.
Few points:
1. Adding images to not-yet-created records - should this be supported or not?
2. Deletion of images - related to previous point if adding images to not-yet-created record; also deletion of a model should be able to remove the images
3. Reordering
4. Resizing/restricting aspect

In the past I have had a lot of headaches because most of the time I needed a drop zone, it also required the possibility to resize the images and also reorder them. For all these operation it would also need APIs exposed.

**Comment by jamesdeacon** [comment]
Is there an updated timeline on this work? I need this functionality for a project of mine but I need to deliver in the next month or so, would be good to know if this is likely to be completed in this time, thanks

**Comment by tabacitu** [comment]
We're working on this right now @jamesdeacon . We're trying to fix this by the end of next month - if this doesn't match your timeline, please plan accordingly.

**Comment by jorgetwgroup** [comment]
Hi @tabacitu, hi @pxpm

i will write here my draft about Dropzone.

Dropzone is compose by:

- Field file
- Operation file (With the help of @pxpm i get i can handle dropzone here)
- Request file

What operations do I hope to cover?

- Upload
- Delete
- Reorder

Main problems:

- Dropzone field dont work correctly on "CREATE" operation of CRUD, because we want to save files on "instance/ID/file.jpeg", example: "monsters/5/5c14ae251fc524522bdac0471ca70f79.jpeg". If we are creating the instance, so we have no ID, my idea is create a temp unique id, and later replace thats temp id for the real one. Like this:

Propose solution:
1. Access to "monster/create"
2. Create a "temp unique id"
3. Upload some files with "temp unique id", like "monsters/tmp_c524522/5c14ae251fc524522bdac0471ca70f79.jpeg"
4. Submit form
5. Replace "temp unique id" for "real id", so "monsters/tmp_c524522/5c14ae251fc524522bdac0471ca70f79.jpeg" rename to "monsters/5/5c14ae251fc524522bdac0471ca70f79.jpeg"

- Dropzone field could lose files when for is Submit and return with errors. I still have no full solution for this.

Cheers.

**Comment by tabacitu** [comment]
Decisions:
1. Where do we save the temporary file? In a temp directory or with a temp name?
    - in a temp directory (eg. `storage/backpack/temp`)
2. Do we use unique IDs for the session?
    - no
3. Do we move or rename temp files to stored files?
    - move
4. Will we have problems when uploading 500 files at once? Or big files?
    - probably 😀 but it's out of scope; this is NOT a scenario this field tries to cover;

(A) Save to `monsters/44/temp_asoufnaofsnaofka.jpeg`
    PROs:
    - it might require less CPU to move/rename 500 files;
    CONs:
    - we need to generate a unique ID when creating (because there is no ID at that point);
    - the field is forcing the developer to save the uploaded files in an IDed folder;
(B) Save to `temp/asoufnaofsnaofka.jpeg` then move to `monsters/asoufnaofsnaofka.jpeg`
    PROs:
    - simpler field (no need to create unique IDs);
    - works on CREATE automatically;
    CONs:
    - folders will be more messy (contain a bunch of disorganized files for different entries);

**Comment by tabacitu** [comment]
## Documentation First Draft

The dropzone field provides a way for the admin to easily upload one or more files, using AJAX requests. The files get uploaded right away to a temporary directory, then moved to a final directory if the form is successfully submitted. To use this field:

*Step 1.* Inside your EntityCrudController, use the `DropzoneOperation`. This will allow this CRUD to receive AJAX file uploads.

*Step 2.* Inside your `setupCreateOperation()` or `setupUpdateOperation()` use the dropzone field:
```php
CRUD::field('photos')->type('dropzone')->disk('public')->prefix('assets/monsters'); // app-name/public/assets/monsters
CRUD::field('attachments')->type('dropzone')->disk('public')->prefix('assets/monsters/'); // app-name/public/assets/monsters
CRUD::field('attachments')->type('dropzone')->disk('public')->prefix(function($entry) {
                                                                return 'assets/monsters/'.$entry->id.'/';
                                                            }); // app-name/public/assets/monsters/44/
```

*Step 3.* Inside the same `setupCreateOperation()` or `setupUpdateOperation()`, define how the files get moved from the temporary directory to the final directory, using Eloquent model events:

```php
Monster::saving(function($entry, $attributes) {
    // at this point, validation has already been passed and
    // $entry will contain the temporary paths;
     
    // TODO: move files to final directory
    // using Laravel's filesystem (the storage disk or something)
    // TODO: construct array with final file paths
    $finalPaths = [];
    // TODO: set the final file paths inside this entry
    $entry->photos = $finalPaths;
});
```

*Step 4.* Remember to validate this field - you can do that using Laravel's `file` validation, including mime types etc. [link]

**Comment by tabacitu** [comment]
Status report: @jorgetwgroup is working on a prototype 🎉 we'll probably have it by Monday 💪
