### ISSUE TITLE
The actions colum in the first column

### ISSUE THREAD

**Issue by AvisenaAlwi** [Laravel-Backpack/community-forum#218]
# Feature Request

### What's the feature you think Backpack should have?

Add the capability to move the actions column to the first column

### Have you already implemented a prototype solution, for your own project?

Not yet, I don't know how to do

### Do you see this as a core feature or an add-on?

core feature

**Comment by tabacitu** [comment]
Hey @AvisenaAlwi ,

Thanks for the idea. It's indeed something we've been considering for a while. Moving this to v6 to maybe do it then, thanks 🙏

**Comment by tabacitu** [comment]
Hey @AvisenaAlwi ,

On further inspection, I've decided this is not worth doing. It would complicate our code, since we've got a lot of other stuff in the first column (checkbox, details row). Since not a lot of people have asked for this, I'm going to decide not to do it. Sorry, but sometimes we have to make this kind of decisions to keep our codebase clean.

Cheers!
