### ISSUE TITLE
Pre-loader for Backpack Laravel in controller

### ISSUE THREAD

**Issue by ainnamran20** [Laravel-Backpack/community-forum#371]
Does Backpack for Laravel support pre-loader animation in controller without any customization from blade?

**Comment by tabacitu** [comment]
I guess people can also change the layout blade file, to make a customization like that? 

This will get easier in Backpack v6, because we're adding full theme support there. So you don't like something? Just create a theme, that works the way _you_ want it.

Since this is the first time this is requested, I'm going to close the issue. We'll reopen if someone else mentions it. If someone stumbles upon this, you can also comment here to re-surface this.

**Comment by blondie63** [comment]
@tabacitu @pxpm 
What about this ? any new loader in v7 ?
