### ISSUE TITLE
Adding multi-language cruds makes existing fields blank

### ISSUE THREAD

**Issue by emogeekface** [Laravel-Backpack/community-forum#401]
I am in the middle to trying to implement multi-language cruds into an existing system however, when I assign a field as translatable in the model and then go to edit an existing entry within the crud any translatable fields which had content previously are now blank - is there a way to get this existing content to show as default if no translations are available for that fields yet?

**Comment by pxpm** [comment]
@emogeekface problem is what is stored inside the database. 

When you add translatable properties to a field, it expects to read from a json in a database. 

To avoid any issues, what I would suggest was a little command `php artisan translations:create-default --table="some_table" --columns="some_column, other_column"` 
Loop over the columns in the table and set the values to valid json translated strings. like `json_encode(['en' => $previousDbValue])`. 

I think the proper solution could/should be on our side, so basically, if it's a simple string, we assume it's the "default" language string. And upon saving, build the proper json to store. 

We will eventually fix it, but I would suggest you use the command for now, as Laravel 10 is launching today, we have v6 on the front door and this translatable part is spread across some fields and the crud panel object, and if we are going to touch it (we will, there is already another PR open to work on translatable stuff), it's better we touch it from the ground up with the fixes.

I will add this as a comment inside that PR, so that we don't forget to take a look at it before merging the PR. 

Cheers

**Comment by emogeekface** [comment]
Perfect, thanks. I'm basically doing this as a workaround already so it's good to know I'm on the right track currently.

Thanks for the quick response!
