### ISSUE TITLE
Can't find variable crud

### ISSUE THREAD

**Issue by darren-glanville** [Laravel-Backpack/community-forum#440]
Some people on some browsers are getting **ReferenceError: crud is not defined** error when viewing the forms pages. 

This is causing some issues as it is then stopping everthing else running.

client.javascript.browser
Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:78.0) Gecko/20100101 Firefox/78.0

Is this something to do with older browsers and can anything be done to allow the JS to still run?

**Comment by promatik** [comment]
Hi @darren-glanville!
Your error is indeed due to the old Firefox version.

We are using the Nullish coalescing assignment `??=` in our code, which was introduced in Firefox **79**, you are using Firefox 78.

Firefox 78 is way outdated, current version is 111.
I'm not sure if we should support such an outdated browser version.

There is dozens of security issues that were fixed in between these 33 versions 😅
Is there any chance you can upgrade your browser?

**Comment by darren-glanville** [comment]
It's not my browser, just a client's one so good it is that I thought.

Is there a list on the website of the minimum browser versions?

Could a message be shown to older browsers that the site will not work with them? Lots of people do not upgrade.

Thanks

**Comment by promatik** [comment]
We do not keep a browser list minimum version, we usually use new features when it is supported by the last 20 versions of all the browsers.

Firefox 78 and bellow are used by 0.53% globally.

@tabacitu, please step in, should we change the nullish coalescing we currently have to support old browsers?

Note that this version is almost 3 years old, and there's been 33 versions released since then.

**Comment by tabacitu** [comment]
Ouch! Sorry for the trouble @darren-glanville . A firefox upgrade should fix it for you!

@promatik I think we're ok keeping nullish coalescing. There's a HUUUGE difference between v78 and v111, nobody should be using v78 any more.

@darren-glanville if you think we're wrong and we SHOULD support Firefox 78, please feel free to make your case, argue with us 😀 We're humans and we make mistakes all the time. I for one am definitely wrong at least once a day 😅

Cheers!
