### ISSUE TITLE
Datepicker field small confusion with variable names

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/community-forum#508]
Received this email:

>In your "date_picker" field template (date_picker.blade.php), a small confusion with the name of the variables $field['datetime_picker_options'] and $field['date_picker_options']
> Because of this, the options work either to change the language or to configure
>
> ![A7AD8104A00C47FB94CCA2445FAF1B26](https://github.com/Laravel-Backpack/community-forum/assets/1032474/e32684c6-cf20-4b45-ada3-f84ccf6b2421)

But I can't really understand what's happening wrong here. Does anybody else understang, and can rephrase so that by stupid brain understand too?

Thanks! If not let's close.

**Comment by smart4you** [comment]
Hi, To add a field like "date_picker" I use the code:
```
[
    'name' => 'birthday',
    'label' => 'Birthday',
    'type' => 'date_picker',
    'date_picker_options' => [
	'todayBtn' => 'linked',
	'todayHighlight' => true,
        'format' => 'dd.mm.yyyy',
	'language' => 'uk'
    ],
],
```
But in the file "date_picker.blade.php" itself, the language is defined through the variable `$field['datetime_picker_options']['language']`. And it turns out that some of the options are defined through variables `$field['date_picker_options']` and the language through the variable `$field['datetime_picker_options']`. 

But I don't know how to explain it to make it clear

**Comment by pxpm** [comment]
Fixed in https://github.com/Laravel-Backpack/PRO/pull/160

Sorry for the mess up @smart4you and thanks for the report 🙏 

Closing this, fix will be released later today. 👌
