### ISSUE TITLE
Add Clickable Rows in Backpack Admin Panel

### ISSUE THREAD

**Issue by helderpgoncalves** [Laravel-Backpack/community-forum#520]
# Feature Request

### What's the feature you think Backpack should have?

The feature I would like to request is the ability to configure rows in Backpack so that they are clickable, allowing users to navigate directly to the show operation for that specific row.

### Have you already implemented a prototype solution, for your own project?

No, I have not implemented a prototype solution for this feature yet. But, If implement a prototype solution by modifying the list.blade.php file and passing data via $this->data['setRowClickable'] = true. This allows users to navigate directly to the show operation for a specific row when clicked.

### Do you see this as a core feature or an add-on?

I see this as an add-on feature. While it can enhance the user experience and navigation within the Backpack admin panel, it may not be considered a core functionality that is necessary for all use cases.

**Comment by tabacitu** [comment]
Hey guys,

Sorry to burst your bubble, but I don't think we should do this. Yes, the implementation is 80% done thanks to the good work that @helderpgoncalves has done, but I still don't think we should. 

Why? Because making the row clickable might NOT be the UX improvement you guys think. Because table rows also have 
- links
- buttons
- checkboxes

If we make the whole row clickable... it is very VERY easy to click NEXT to a link/button/checkbox on a row, especially on mobile/tablet... and the behaviour would be different from what you expect.

So I'd rather not to this, sorry. I think keeping it simple is best here.

Sorry this didn't move forward @helderpgoncalves . If you disagree please come back with arguments, like everyone else, I'm wrong at least once a day and this might be one of those cases 😅 But it doesn't look like the PROs outweigh the CONs here. Thanks for opening up the issue and sharing your code, nonetheless.

Cheers!
