### ISSUE TITLE
Backpack 5.x, sidebar width

### ISSUE THREAD

**Issue by telemaco230** [Laravel-Backpack/community-forum#537]
How can I customize sidebar size?

**Comment by promatik** [comment]
Hi @telemaco230!
In order to resize the sidebar you must override 3 CSS rules on your side;

1) Set the `width` of the `.sidebar`
2) Set the `flex-basis` also on the `.sidebar`
3) Set the `width` on the `.sidebar .nav`

I set all of those to `300px` and this is the result;

![image](https://github.com/Laravel-Backpack/community-forum/assets/1838187/120247e2-977b-48ab-89fd-24772538a744)
