### ISSUE TITLE
Laravel BackPack Developer Addon - Unuseable with Vagrant

### ISSUE THREAD

**Issue by webboty** [Laravel-Backpack/community-forum#553]
Hello Team Backpack, I was a big fan of the backpack developer add-on as it makes certain tasks quicker. However the developer add-on does not work in the scope of a vagrant setup (which is one of the approaches recommended by Laravel to develop locally).

I have to completely remove and reinstall the backpack developer add-on in order to make it work temporarily.
This is quite time consuming (and takes more time then the time saved by using the add-on), especially since the add-on stops working quickly after the re-install. So unfortunately the developer add on is 100% useless as of now. :-(

Attached is a screenshot of a message that i am getting when i try to create a CRUD for a model.

I am using Laravel 9 and Backpack 5.

Any recommendation/fix to make the add-on work in the scope of a vagrant setup is appreciated.

Thanks
Tony
![2023-07-05_16-29-25](https://github.com/Laravel-Backpack/community-forum/assets/47084177/a377f84b-614e-428f-906d-6ec591acb5d1)

**Comment by pxpm** [comment]
Hey @webboty thanks 

So you are able to install devtools, you create what? One model and it stops working ? 

Did you changed something in your configuration ? 

Can you record a gif or something of you using it and it breaking ? 

Cheers

**Comment by webboty** [comment]
Hi @pxpm ... thanks for getting on this issue so quickly. :-) 

Yes, i have to remove the dev-addon and add it again via composer. Then re-install it. No configs changed, the default are used. Then i can go in pick one of my models that previously showed that error message and actually create a CRUD etc. as i am used too. 

Then when i try to do this again ... hours later ... I get the error again and the whole cycle repeats.
So it has nothing to do with the install itself or the models being used. I think it is because of the way vagrant works. It syncs the codebase that runs in the headless virtual machine with the codebase that is stored on the master/parent system.

In my case I develop on mac osx and and the laravel backpack app runs on vagrant which in my case is ubuntu based.

I am always able to visit the page ... admin/devtools/model ... (even though it takes long to show everything). Then once i click on an action ... like generate crud ... i get the error message of the screenshot.

**Comment by pxpm** [comment]
Hello @webboty 

So I've sent quite some time setting up Homestead an try to reproduce your issue but I was not able.

I gave it a shot because like you said Homestead/Vagrant work by a sync mechanism with the VM, and we use the file inode as the identifier for the models in Devtools. 
It was possible that somehow that inode changed in the sync or something similar and raised the errors you describe. 

Unfortunately I was not able to reproduce your issue. I tried shut down the vm, restarting it, restarting computer, and everything kept working as expected. 

My setup is:
Windows 11
Homestead 13
VirtualBox 6.1

If you are using Vagrant without Homestead it may be some issue in your sync mechanism, I don't know if Homestead does something differently, but it's possible it does. 

If you can provide me specific steps I can try take to reproduce your issue otherwise I don't know what I can do more. 

Cheers

**Comment by pxpm** [comment]
Cleaning up my board.

Comments are not locked so we can keep the conversation if needed.

Cheers 🙏
