### ISSUE TITLE
CKEditor toolbars in Backpack v6

### ISSUE THREAD

**Issue by prodixx** [Laravel-Backpack/community-forum#559]
Hi guys!

I'm giving a shot to V6 for a new project and i've noticed that ckeditor and wysiwyg fields no longer loads the same toolbars like in V5. Also extra_plugins doesn't work anymore on them. 

```
[
    'name' => 'full_details',
    'label' => 'Detalii',
    'type' => 'wysiwyg',
    // 'extra_plugins' => ['colordialog', 'colorbutton', 'justify'],
    'options' => [
        'customConfig' => asset('js/ckeditor_config.js'),
    ],
    'tab' => 'General',
    'wrapperAttributes' => ['class' => 'form-group col-md-12'],
],
```
I;ve tried to load custom config (from v5) but with no results.

Any ideas how i can accomplish this?

Thanks.

**Comment by tabacitu** [comment]
Hmm you are correct - because those fields are using Basset now, the process of using extra plugins has changed. @promatik could you please help @prodixx here with steps on how to do it? Do we need to document this in the field docs? Do we need an upgrade guide for this? 🤷‍♂️

**Comment by promatik** [comment]
Hi @prodixx!
Indeed, CKEditor v5 made the process of customizing the interface quite different.

Now you'll need to go to [CKEditor 5 Online builder](https://ckeditor.com/ckeditor-5/online-builder/);

1) **Choose plugins**
![image](https://github.com/Laravel-Backpack/community-forum/assets/1838187/24e2e57a-ee04-48c7-a926-1daf5d406da1)

2) **Customize the view**
![image](https://github.com/Laravel-Backpack/community-forum/assets/1838187/7bdf7051-ec08-4f95-90cb-a6d54ae7eb81)

3) **Export your build**
![image](https://github.com/Laravel-Backpack/community-forum/assets/1838187/39b5d7be-bc7c-45dc-96d5-0e6b50bdfaf5)

---

After this, you can now use your own build on backpack 👌
I've placed the following files at `resources\assets\ckeditor`:
- `ckeditor.js` (the exported ckeditor build)
- `ckeditor-init.js` (my ckeditor initializer)

Since you're using a costum build, backpack will no longer initialize it, so you'll need to do it on `ckeditor-init.js`:
```js
let element = document.querySelector('[name="your-ckeditor-fieldname"]');
ClassicEditor.create(element, element.dataset.options);
```

And then create the field with the `custom_build`:

```php
CRUD::addField([
    'name' => 'ckeditor',
    'type' => 'ckeditor',
    'custom_build' => [
        resource_path('assets/ckeditor/ckeditor.js'),
        resource_path('assets/ckeditor/ckeditor-init.js'),
    ],
]);
```

---

And that's it, I added the underline plugin to my custom ckeditor:
![image](https://github.com/Laravel-Backpack/community-forum/assets/1838187/fed678da-b279-41ff-b56e-a4bb1a798674)

**Comment by pxpm** [comment]
Just to add a note that if you have too much stuff customized and CKeditor 4 is more than enough for your needs, you can just go to v5 branch, copy the ckeditor file as `ckeditor_v4.blade.php` and use it instead of the ckeditor Backpack provides. 

I would just probably advise to also change the `<scripts>` etc to be loaded through @basset and use CoreUIv2 theme because of Bootstrap 4, I think ckeditor has issues with BS 5. 

Nice tutorial @promatik 🙏 and thanks for answering this on on my turn!

Cheers

**Comment by tabacitu** [comment]
Awesome! @prodixx let us know if this isn't what you wanted, or have feedback. We'll reopen if needed. Cheers!

**Comment by prodixx** [comment]
@adrienne you can match all ckeditor fields in the page like this: 

```
let elements = document.querySelectorAll('[data-init-function="bpFieldInitCKEditorElement"]');

elements.forEach(function (element) {
    ClassicEditor.create(element, element.dataset.options);
});

```

**Comment by adrienne** [comment]
@prodixx yeah, matching them wasn't the problem -- it was causing all sorts of double-initialization problems and such.

This way seems cleaner.

**Comment by prodixx** [comment]
i have 4 fields on page and i didn't saw anything fishy . now that you've said it, ill double check it...

**Comment by lebedynskyi** [comment]
I don't know how.. Did the same on fresh install - works fine..
