### ISSUE TITLE
[Feature Request] Save and clone button in edit view

### ISSUE THREAD

**Issue by de-raaf-media** [Laravel-Backpack/community-forum#567]
When an admin created a crud it would be great for the workflow if there would be a save and clone option. Especially when entering loads of data.

As far as I know this is not an option currently.

Mark

**Comment by tabacitu** [comment]
Hey @de-raaf-media ,

You can do that in your own projects pretty easily by [adding a SaveAction](https://backpackforlaravel.com/docs/6.x/crud-save-actions#addsaveaction-array-saveaction) in your `setup()` OR `setupCreateOperation()` and `setupUpdateOperation()` methods:

```php
CRUD::addSaveAction([
    'name' => 'save_and_clone',
    'redirect' => function($crud, $request, $itemId) {
        // TODO: clone the current item
        // TODO: create the URL you want the admin redirected to 
        return $crud->route;
    }, // what's the redirect URL, where the user will be taken after saving?

    // OPTIONAL:
    'button_text' => 'Save and clone', // override text appearing on the button
    'visible' => function($crud) {
        return true;
    }, // customize when this save action is visible for the current operation
    'referrer_url' => function($crud, $request, $itemId) {
        return $crud->route;
    }, // override http_referrer_url
    'order' => 1, // change the order save actions are in
]);
```

What's a little more difficult is if you want to add it to ALL your CrudControllers. In that case you can do:
- create a CrudController in your project that extends Backpack's CrudControllers; add the saveAction there, inside the `setup()` method;
- have all your UserCrudController (etc) extend your CrudController instead of Backpack's, making sure inside the `setup()` method you also do `parent::setup()`;
 
I'll leave this open for a while. If more people think it'd be useful to their admins, we can add it as a default. 

Thanks for the suggestion.
Cheers!

**Comment by de-raaf-media** [comment]
Very nice! Gonna try it.

**Comment by tabacitu** [comment]
We've decided not to do this in the core, since it's unusual and devs can easily do it in their own projects. Closing, let's focus!
