### ISSUE TITLE
Theme view fallbacks not complete

### ISSUE THREAD

**Issue by Ronnos** [Laravel-Backpack/community-forum#583]
In the documentation: https://backpackforlaravel.com/docs/6.x/base-themes#theme-view-fallbacks-1 it says that there are 5 possible fallbacks:
```
resources/views/admin/theme-custom/path/to/view.blade.php
resources/views/vendor/backpack/theme-tabler/path/to/view.blade.php
vendor/backpack/theme-tabler/resources/views/path/to/view.blade.php
resources/views/vendor/backpack/ui/path/to/view.blade.php
vendor/backpack/crud/src/resources/views/ui/path/to/view.blade.php
```

However, I think this is wrong, there are only 3 when I look at the backpack_view() function at backpack/crud/src/helpers.php:

```php
function backpack_view($view)
    {
        $viewPaths = [
            config('backpack.ui.view_namespace').$view,
            backpack_theme_config('view_namespace_fallback').$view,
            'backpack.ui::'.$view,
        ];

        foreach ($viewPaths as $view) {
            
            //if $view contains string then
            if (str_contains($view, 'topbar_right_content')) {
                echo $view;
                echo '<br>';
            }

            if (view()->exists($view)) {
                return $view;
            }
        }

        dd('Could not find Backpack view ['.$view.'] in theme namespace, fallback namespace nor UI namespace.');
    }
```

**Comment by tabacitu** [comment]
Hi @Ronnos ,

Indeed it looks like it's only 3. But actually Laravel has built-in fallbacks for some of them. If you do `view()->exists('some.package::file')` then Laravel will check for views:
- in published views  - `resources/views/vendor/some/package/resources/views/file.blade.php`
- then if that doesn't exist, in the vendor directory - `vendor/some/package/resources/views/file.blade.php`

So I believe the docs are correct. Please let me know if your investigations turns our otherwise. I'm wrong at least once a day, like everybody else 😅
