### ISSUE TITLE
CkEditor(Wysiwyg) file upload

### ISSUE THREAD

**Issue by izica** [Laravel-Backpack/community-forum#641]
Hello, in backpack/pro, the CKEditor file upload doesn't function as intended. 
When attempting to upload a file, nothing happens. 
The console displays the error message "filerepository-no-upload-adapter." 
I resolved this issue by modifying the "ckeditor.blade.php" file and developing a customized upload adapter. 
With fix when uploading a file, the file is moved to the "/uploads/ckeditor/{modelName}" directory.

How can I pr this fix?

**Comment by izica** [comment]
When uploading a file, the file is moved to the "/uploads/ckeditor/{modelName}" directory.

**Comment by tabacitu** [comment]
Hi @izica - ouch, I wasn't aware. Thanks for letting us know, and for providing the fix. 

It's tricky to create a PR to PRO, since it's closed-source. Can you please send the `ckeditor.blade.php` blade file to hello@backpackforlaravel.com ? I'll pick it up and create the PR for you.

Thanks a lot!

**Comment by izica** [comment]
@tabacitu 
I've sent the message with fix to email.

This issue emerged because CKEditor was upgraded from version 4 to 5, but CKEditor is not fully backwards compatible.

**Comment by haniramadhan-kkp** [comment]
I amn still waiting for the bug fix? Can I use other template or backpack version to use WYSIWYG editor?

**Comment by pxpm** [comment]
@haniramadhan-kkp sorry for the time it took me to get back here. 

I've got the info needed, and will work on this during this week. 

Thanks for your patience. 

Cheers

**Comment by adriallongarriu** [comment]
@pxpm any news on this? my issue([#5323](https://github.com/Laravel-Backpack/CRUD/issues/5323)) was closed 3 weeks ago only to move the conversation here...

**Comment by pxpm** [comment]
Sorry @adriallongarriu since this is in the private repo it seems that we are not moving foward, but we are currently making progress on it, and already have a partial integration working. I think by the end of this week at most we should be able to ship it.

here is the status of it: 
![image](https://github.com/Laravel-Backpack/community-forum/assets/7188159/1ab28657-6f96-44f9-8e6e-14af6e747530)

**Comment by kevinartimedia** [comment]
![image](https://github.com/Laravel-Backpack/community-forum/assets/112622409/a8396cfc-7432-4526-b60e-221e159f65e4)
![image](https://github.com/Laravel-Backpack/community-forum/assets/112622409/99696062-7306-4769-8ec5-4cbf6b6dd560)

Hi!
How is this topic? It doesn't work for us.

**Comment by pxpm** [comment]
Hey @kevinartimedia we have this "pretty much ready" in our repo, but we've decided to push the fix for this upstream in the Laravel community package. The reason is that we would need a lot of hackywaky stuff and make people lifes very difficult to upgrade if we push this change in our repo instead of the upstream.

Unfortunately we didn't had the time to finish this, the PR's need need to be refactored so that they can be submitted to the upstream package. 
This is in my backlog, I just have other priorities come up in the meanwhile. I hope I can give everyone a happy new year gift on this one 🙏 

Cheers, and thanks for your patience.

**Comment by FilippoCalabrese** [comment]
Any update?

**Comment by zisakmc** [comment]
The error lead me here, hope update available soon

**Comment by FilippoCalabrese** [comment]
> The error lead me here, hope update available soon

Using TinyMCE field type seems to fix the issue. It is not a solution but is a workaround to me 😄

**Comment by wfgm5k2d** [comment]
This problem still exists in my backpack 6
Any solutions?

**Comment by pxpm** [comment]
Elfinder was added back to CKEditor on backpack/pro 2.2.1 released today. 

The custom uploader (for drag 'n drop and image upload) will follow after we merge https://github.com/Laravel-Backpack/CRUD/pull/5478 that would allow us to create an uploader for ckeditor too. 

Please see the updated docs here: https://backpackforlaravel.com/docs/6.x/crud-fields#ckeditor-pro

**Comment by pxpm** [comment]
I will leave this issue open until we add the Custom Uploader (like we are adding for easymde).

**Comment by pxpm** [comment]
We will not add a custom uploader to ckeditor. Not in the foreseable future. 

It works with elfinder, and we will keep it that way. 

Cheers
