### ISSUE TITLE
Integrate with Jetstream

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/community-forum#692]
This client paints a better picture than I could:

> Also there is (to my point of view) a lack of good interaction with current Jetstream version and a page (or a git repo fully prepared) about it would be quite nice. It's the biggest starting point for most people around lately and we had to struggle a little about it.

I think they're totally right. A lot of people nowadays start with Jetstream, so we will be judged by how good their Jetstream + Backpack experience is. Time to take a look and improve the UX.

**Comment by MattLoyeD** [comment]
Thanks for pushing this subject for the commnity @tabacitu , we've achieved partial (but good) integration of jetstream with backpack.

Replace these three values in config/backpack/base.php :
`
<?php

return [
// ...
'setup_auth_routes' => false, // instead of 'true'
'guard' => 'web', // instead of 'backpack'
 // 'passwords' => 'users', // disabled to be decorelated, not sure it serves a purpose but we kept it
// ...
];
`

Next thing to be fully integrated with jetstream would be to make 2FA mandatory for some roles (using [spatie/laravel-permission](https://github.com/spatie/laravel-permission) package), but I guess this is a bit off topic. However most users start with jetstream mostly because it brings really clear and secured path for a great boilerplate with 2FA already included.

**Comment by tabacitu** [comment]
Cleaning up old issues. Since Jetstream doesn't have a Bootstrap version, it's pretty much impossible to "integrate with it".

So we're working on something BETTER. Creating a starter kit LIKE Jetstream, that uses our favorite stack right now - the BALL stack (Bootstrap, Any-Js-you-want, Laravel, Livewire). This will be super-easy to integrate with Backpack, and a solid alternative to Jetstream. It's 80% done and will be available here once it's done - https://github.com/tabacitu/scratch-app-starter

**Comment by tabacitu** [comment]
Let me put a gif here too, it's EXCITING:

![348979938-0a82d0da-a9d5-49cc-a09e-57bace3e209f](https://github.com/user-attachments/assets/37be137d-a630-42bb-884d-74d68ef38e65)

**Comment by dvdmnc** [comment]
Hey
Is it done ?
We just bought backpack pro with devtool, added spatie/laravel-permission, laravel backpack log manager and laravel backpack language switcher for the admin panel
We use laravel jetstream with a react front end for the client side 
Even with little data added to the database the app is very slow, and we don't understand why
A starter kit like the one you're building would therefore, I think, be the best option
