### ISSUE TITLE
Ids instead of name.

### ISSUE THREAD

**Issue by backpack-operations** [Laravel-Backpack/community-forum#700]
Hello team,

I just received this on email: "Hi,

I am using editable select, and while exporting I am getting ids instead of name, can you suggest any workaround to get relation name.

Thanks"

**Comment by pxpm** [comment]
I haven't tested it @backpack-operations , but from the gist of it, it seems a bug in Editable-Columns. 

@promatik can you have a look at this? Probably it would be easier for you to find and fix this (if it's a relatively simple fix), otherwise we may postpone this to be fixed by the new export operation.

**Comment by promatik** [comment]
I tried this with our demo, added a column with a relation to the categories, and it works as expected.
It exports the relation name, not the ID.

![image](https://github.com/Laravel-Backpack/community-forum/assets/1838187/f42cfbd1-9025-4e3e-ab3c-25006fcdb580)

![image](https://github.com/Laravel-Backpack/community-forum/assets/1838187/7114f732-0e95-4292-b2de-7f8f12ed15e9)

Anyway, we will soon release a feature that will allow to create custom list views, and that way developers will be able to create multiple custom exports for the same CRUD. https://github.com/Laravel-Backpack/PRO/pull/218.

@backpack-operations I'll close this one for now, let me know (re-open the issue) if the user provides us more information 👌
