### ISSUE TITLE
Editing, creating and showing enteties in pop-up

### ISSUE THREAD

**Issue by backpack-operations** [Laravel-Backpack/community-forum#729]
Hello team,
I just received this on email:
"Hello! could you help and tell how we can edit and create entities not on a separate page but in pop-up. Is it possible?"

**Comment by phpfour** [comment]
Hey @backpack-operations,

Thanks for bringing it up here. Please point the customer to this section of the documentation: 

https://backpackforlaravel.com/docs/6.x/crud-operation-inline-create

It should suffice their need. 

Thanks!

**Comment by tabacitu** [comment]
I wouldn't say that. From what I understand, the dev wants to open the Create and Edit forms in a modal, instead of a separate page. It's not related to "inline create" directly.

So what I would answer is that **NO, there is no built-in way in Backpack to do that**. **You cannot toggle a switch and have the Create & Update operations in modals.** You can code those bits yourself... but I wouldn't recommend it. You would have too much customization, and that would prevent you from receiving upgrades in the future.

Hope it helps!

**Comment by dluccajose** [comment]
@tabacitu how about make this a feature for future releases? like for example make super easy to call the inline-create modal that comes with the InlineCreateOperation from any page or section of backpack
