### ISSUE TITLE
[Bug] Route [province-inline-create] not defined.

### ISSUE THREAD

**Issue by tringuyenduc2903** [Laravel-Backpack/community-forum#847]
# Bug report

### What I did

Create a field with type **relationship**

### What I expected to happen

Just set the required properties for the field as shown in the documentation

1. ```php artisan backpack:crud address/province```

in **ProvinceCrudController** file
```php
    use InlineCreateOperation;
```

2. ```php artisan backpack:crud address/district```

in **DistrictCrudController** Controller file
```php
    use FetchOperation;

    /**
     * Define what happens when the Create operation is loaded.
     *
     * @see https://backpackforlaravel.com/docs/crud-operation-create
     * @return void
     */
    protected function setupCreateOperation()
    {
        ...
        CRUD::addField([
            'type' => 'relationship',
            'name' => 'province_id',
            'ajax' => true,
            'inline_create' => [
                'entity' => 'province',
            ]]);
        ...
    }

    /**
     * Gets items from database and returns to selects.
     *
     * @return JsonResponse|Collection|LengthAwarePaginator|Paginator
     */
    protected function fetchProvince()
    {
        return $this->fetch(Province::class);
    }
```
in **District** Model file
```php
    /**
     * @return BelongsTo
     */
    public function province(): BelongsTo
    {
        return $this->belongsTo(Province::class);
    }
```

3. ``` php artisan make:migrate create_address_tables ```

```php
/**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('provinces', function (Blueprint $table) {
            $table->id();
            $table->bigInteger('code')->unique();
            $table->string('name', 40);
            $table->tinyInteger('division_type');
            $table->softDeletes();
        });

        Schema::create('districts', function (Blueprint $table) {
            $table->id();
            $table->bigInteger('code')->unique();
            $table->string('name', 40);
            $table->tinyInteger('division_type');
            $table->foreignId('province_id')
                ->nullable()
                ->constrained()
                ->onDelete('set null')
                ->cascadeOnUpdate();
            $table->softDeletes();
        });
    }
```
### What happened

Exception Occurred: **Route [province-inline-create] not defined.**

![image](https://github.com/Laravel-Backpack/community-forum/assets/101564593/bd330952-8aa8-49a4-9535-e805ea10db75)

### What I've already tried to fix it

```php
namespace Backpack\Pro\Http\Controllers\Operations;
...
trait InlineCreateOperation
{
    ...
    protected function setupInlineCreateRoutes($segment, $routeName, $controller)
    {
        Route::post($segment.'/inline/create/modal', [
           \\ From: 'as'        => $segment.'-inline-create',
           \\ To:   'as'        => $routeName.'-inline-create',

           \\ From: 'as'        => $segment.'-inline-create-save',
           \\ To:   'as'        => $routeName.'-inline-create-save',
            ...
        ]);
    }
``` 

### Is it a bug in the latest version of Backpack?

After I run backpack ```composer update backpack/crud``` the error it still persists

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

![image](https://github.com/Laravel-Backpack/community-forum/assets/101564593/7aea2142-efe6-4e9e-b6e0-b6cf1c9e0c9b)

**Comment by tringuyenduc2903** [comment]
@karandatwani92 Hello, do you mind my asking questions about the progress of the problem?

My issue is rated as Important, I even point out the error in your source code and how to fix it. But the processing time seems to take longer than expected. So disappointed with the Pro service from Backpack

**Comment by pxpm** [comment]
Hello @tringuyenduc2903 

I don't know why this is categorized as a MUST, as it's not even confirmed it's a bug nor there are any steps to reproduce said error. 

We couldn't do something like what you propose in a minor version, as it would be a breaking change. 

But I think the error is the fact that you are missing adding the `InlineCreateOperation` in your secondary CrudController, in your case it seems to be `ProvinceCrudController`. 

That operation should be registered in BOTH controllers as stated in the docs. 

There is an extra route registered that's never called (the one you pointed out). That's due to architectural limitations on how we use the Operations. Maybe using some meta-programming we may be able to remove the registration of that extra route, but it's not a priority. 

Let me know if you still experience the issue, if so, can you please provide me stripped down controllers of where you are using the operation ? 

Sorry it took so much time to get back here. 

Cheers

**Comment by tringuyenduc2903** [comment]
@pxpm Sorry for being impatient, I've updated the information on how to reproduce the error. If you have difficulty recreating, please comment here. I was really impatient so I couldn't control my words

**Comment by pxpm** [comment]
Hey @tringuyenduc2903 no issues. This shouldn't be so much time without a response, that's unacceptable I agree with you 100% and sorry for that. 

Like I said, I think you are missing adding the `InlineCreateOperation` in one of your Controllers, in this case `DistrictCrudController` as you already have it in `ProvinceCrudController`. 

Can you confirm ? 

Cheers

**Comment by tringuyenduc2903** [comment]
@pxpm 
1. **InlineCreateOperation** at **Address/DistrictCrudController** will create **router_name** "_address/district-inline-create_". => **Not necessary**
2. **InlineCreateOperation** at **Address/ProvinceCrudController** will create **router_name** "_address/province-inline-create_".

3. In fact, the field_type relationship needs to get the **router_name** "_province-inline-create_", so the exception "**Route [province-inline-create] not defined.**"

Do you understand the problem?

**Comment by tringuyenduc2903** [comment]
@pxpm This error can be fixed in no more than 1 minute. I mentioned it in the article
```php
namespace Backpack\Pro\Http\Controllers\Operations;
...
trait InlineCreateOperation
{
    ...
    protected function setupInlineCreateRoutes($segment, $routeName, $controller)
    {
        Route::post($segment.'/inline/create/modal', [
           \\ From: 'as'        => $segment.'-inline-create',
           \\ To:   'as'        => $routeName.'-inline-create',

           \\ From: 'as'        => $segment.'-inline-create-save',
           \\ To:   'as'        => $routeName.'-inline-create-save',
            ...
        ]);
    }
```

**Comment by pxpm** [comment]
Hey @tringuyenduc2903 I understand the fix is not that complicated. 

I appreciate you took the time, and have a working solution for it, but we cannot merge it without a Breaking Change, because all the developers using this Operation until now, are expecting the URL to use the $segment, not $routeName. 

To do that breaking change, we need to bump the Major version, to bump the major in this package we need to have an upgrade guide, and notify developers about new Major, otherwise they don't get the updates.

We'd rather do all breaking changes at once, when we release a major version for all the packages. Somewhere in a few months this year. 

Does my proposed solution work for you ? 

Cheers

**Comment by pxpm** [comment]
Hey @tringuyenduc2903 

if you have time to get back here, please let me know if my proposed solution worked for you. In case it doesn't, that is a bug we can fix for sure, but I hope you solved the issue by now. 

Let me know. Cheers

**Comment by pxpm** [comment]
> @pxpm I just reviewed the source code, the value of **$segment** is now **province** instead of **address/province**. Boom! So the error is gone
> 
> ![image](https://private-user-images.githubusercontent.com/101564593/318073392-df4fd82d-0baf-48c1-8590-a2e598a47543.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE3MjQyMzIsIm5iZiI6MTcxMTcyMzkzMiwicGF0aCI6Ii8xMDE1NjQ1OTMvMzE4MDczMzkyLWRmNGZkODJkLTBiYWYtNDhjMS04NTkwLWEyZTU5OGE0NzU0My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyOVQxNDUyMTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMzU1ZTNjMmY0MmJmMDhkZTE0NGNiZDQxMjQ2MGJjNDkyMDMyNDJkMTNiNjZkN2ZmMTZhODViYWQzZjc2MDNlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5mb4aDuSRNPjefC0a0sPniH3bYRvjAUeT8SpQ7y0yw4)

By that you mean, you changed your `Route::crud()` definition right ? 

I just want to make sure we are on the same page, like I told you, I have already a PR or two in line for the next major version where I can do some breaking changes, and I am trying to make sure next time I mess with it, I get it right! 

Thanks for you time and patience here. I acknowledge you are a very dedicated person, and I really appreciate all your efforts reporting bugs. I understand that sometimes it gets frustrating, but be sure everything you said is taken into consideration. 

Cheers

**Comment by tringuyenduc2903** [comment]
@pxpm  I already know the main cause of the error

```php
Route::crud('address/province', ProvinceCrudController::class);
```
 will generate **$segment** is **address/province**
and

```php
Route::prefix('address')->group(function () {
    Route::crud('province', ProvinceCrudController::class);
    Route::crud('district', DistrictCrudController::class);
    Route::crud('ward', WardCrudController::class);
});
```
will create **$segment** is **province**

However, editing **route_name** is still necessary, because it follows the same Route creation principle as **ListOperation**, **CreateOperation**, **UpdateOperation**,...
```php
        Route::get($segment.'/', [
            'as' => $routeName.'.index',
            'uses' => $controller.'@index',
            'operation' => 'list',
        ]);
```

**Comment by pxpm** [comment]
Indeed. That's the problem. 👍 

I don't think we can use routeName tho. I think the solution to work on all use-cases would need to be some url parsing. 

The issue I have identified to fix in next version, I think will fix this too, because they are very similar. 

For example, in a nested CRUD, like: https://github.com/Laravel-Backpack/demo/blob/main/app/Http/Controllers/Admin/PetShop/OwnerPetsCrudController.php we have the same issue. 

I think if I fix it for nested cruds, it will be fixed for this scenario too. 

Thanks, I will try to remember to take this into consideration. 

Cheers
